version: '3'

services:
    # Frontend
  web:
    image: {{IMAGEM_NOME_WEB}}:{{ IMAGEM_TAG }}
    restart: {{RESTART_POLICY}}
    container_name: {{ CONTAINER_NOME_WEB }}
    ports:
      - '{{HTTP_PORT}}:80'
      - '{{HTTPS_PORT}}:443'
    volumes:
      - {{ INSTALACAO_PASTA_WEB }}:/config:Z
      - {{ INSTALACAO_PASTA_WEB }}/transcripts:/usr/share/jitsi-meet/transcripts:Z
      - {{ INSTALACAO_PASTA_WEB }}/imagens:/usr/share/jitsi-meet/images:Z
    environment:
      # - ENABLE_LETSENCRYPT={{ENABLE_LETSENCRYPT}}
      # - ENABLE_HTTP_REDIRECT={{ENABLE_HTTP_REDIRECT}}
      # - DISABLE_HTTPS={{DISABLE_HTTPS}}
      # - LETSENCRYPT_DOMAIN={{LETSENCRYPT_DOMAIN}}
      # - LETSENCRYPT_EMAIL={{LETSENCRYPT_EMAIL}}
      # - LETSENCRYPT_USE_STAGING={{LETSENCRYPT_USE_STAGING}}
      # - PUBLIC_URL={{PUBLIC_URL}}
      # - TZ={{TZ}}
      # - AMPLITUDE_ID={{AMPLITUDE_ID}}
      # - ANALYTICS_SCRIPT_URLS={{ANALYTICS_SCRIPT_URLS}}
      # - ANALYTICS_WHITELISTED_EVENTS={{ANALYTICS_WHITELISTED_EVENTS}}
      # - BRIDGE_CHANNEL={{BRIDGE_CHANNEL}}
      # - BRANDING_DATA_URL={{BRANDING_DATA_URL}}
      # - CALLSTATS_CUSTOM_SCRIPT_URL={{CALLSTATS_CUSTOM_SCRIPT_URL}}
      # - CALLSTATS_ID={{CALLSTATS_ID}}
      # - CALLSTATS_SECRET={{CALLSTATS_SECRET}}
      # - CHROME_EXTENSION_BANNER_JSON={{CHROME_EXTENSION_BANNER_JSON}}
      # - CONFCODE_URL={{CONFCODE_URL}}
      # - CONFIG_BOSH_HOST={{CONFIG_BOSH_HOST}}
      # - CONFIG_EXTERNAL_CONNECT={{CONFIG_EXTERNAL_CONNECT}}
      # - DEPLOYMENTINFO_ENVIRONMENT={{DEPLOYMENTINFO_ENVIRONMENT}}
      # - DEPLOYMENTINFO_ENVIRONMENT_TYPE={{DEPLOYMENTINFO_ENVIRONMENT_TYPE}}
      # - DEPLOYMENTINFO_USERREGION={{DEPLOYMENTINFO_USERREGION}}
      # - DIALIN_NUMBERS_URL={{DIALIN_NUMBERS_URL}}
      # - DIALOUT_AUTH_URL={{DIALOUT_AUTH_URL}}
      # - DIALOUT_CODES_URL={{DIALOUT_CODES_URL}}
      # - DROPBOX_APPKEY={{DROPBOX_APPKEY}}
      # - DROPBOX_REDIRECT_URI={{DROPBOX_REDIRECT_URI}}
      # - ENABLE_AUDIO_PROCESSING={{ENABLE_AUDIO_PROCESSING}}
      # - ENABLE_AUTH={{ENABLE_AUTH}}
      # - ENABLE_CALENDAR={{ENABLE_CALENDAR}}
      # - ENABLE_FILE_RECORDING_SERVICE={{ENABLE_FILE_RECORDING_SERVICE}}
      # - ENABLE_FILE_RECORDING_SERVICE_SHARING={{ENABLE_FILE_RECORDING_SERVICE_SHARING}}
      # - ENABLE_GUESTS={{ENABLE_GUESTS}}
      # - ENABLE_IPV6={{ENABLE_IPV6}}
      # - ENABLE_LIPSYNC={{ENABLE_LIPSYNC}}
      # - ENABLE_NO_AUDIO_DETECTION={{ENABLE_NO_AUDIO_DETECTION}}
      # - ENABLE_P2P={{ENABLE_P2P}}
      # - ENABLE_PREJOIN_PAGE={{ENABLE_PREJOIN_PAGE}}
      # - ENABLE_WELCOME_PAGE={{ENABLE_WELCOME_PAGE}}
      # - ENABLE_CLOSE_PAGE={{ENABLE_CLOSE_PAGE}}  
      # - ENABLE_RECORDING={{ENABLE_RECORDING}}
      # - ENABLE_REMB={{ENABLE_REMB}}
      # - ENABLE_REQUIRE_DISPLAY_NAME={{ENABLE_REQUIRE_DISPLAY_NAME}}
      # - ENABLE_SIMULCAST={{ENABLE_SIMULCAST}}
      # - ENABLE_STATS_ID={{ENABLE_STATS_ID}}
      # - ENABLE_STEREO={{ENABLE_STEREO}}
      # - ENABLE_SUBDOMAINS={{ENABLE_SUBDOMAINS}}
      # - ENABLE_TALK_WHILE_MUTED={{ENABLE_TALK_WHILE_MUTED}}
      # - ENABLE_TCC={{ENABLE_TCC}}
      # - ENABLE_TRANSCRIPTIONS={{ENABLE_TRANSCRIPTIONS}}
      # - ETHERPAD_PUBLIC_URL={{ETHERPAD_PUBLIC_URL}}
      # - ETHERPAD_URL_BASE={{ETHERPAD_URL_BASE}}
      # - GOOGLE_ANALYTICS_ID={{GOOGLE_ANALYTICS_ID}}
      # - GOOGLE_API_APP_CLIENT_ID={{GOOGLE_API_APP_CLIENT_ID}}
      # - INVITE_SERVICE_URL={{INVITE_SERVICE_URL}}
      # - JICOFO_AUTH_USER={{JICOFO_AUTH_USER}}
      # - MATOMO_ENDPOINT={{MATOMO_ENDPOINT}}
      # - MATOMO_SITE_ID={{MATOMO_SITE_ID}}
      # - MICROSOFT_API_APP_CLIENT_ID={{MICROSOFT_API_APP_CLIENT_ID}}
      # - NGINX_RESOLVER={{NGINX_RESOLVER}}
      # - PEOPLE_SEARCH_URL={{PEOPLE_SEARCH_URL}}
      # - RESOLUTION={{RESOLUTION}}
      # - RESOLUTION_MIN={{RESOLUTION_MIN}}
      # - RESOLUTION_WIDTH={{RESOLUTION_WIDTH}}
      # - RESOLUTION_WIDTH_MIN={{RESOLUTION_WIDTH_MIN}}
      # - START_AUDIO_ONLY={{START_AUDIO_ONLY}}
      # - START_AUDIO_MUTED={{START_AUDIO_MUTED}}
      # - START_BITRATE={{START_BITRATE}}
      # - START_VIDEO_MUTED={{START_VIDEO_MUTED}}
      # - TESTING_CAP_SCREENSHARE_BITRATE={{TESTING_CAP_SCREENSHARE_BITRATE}}
      # - TESTING_OCTO_PROBABILITY={{TESTING_OCTO_PROBABILITY}}
      # - XMPP_AUTH_DOMAIN={{XMPP_AUTH_DOMAIN}}
      # - XMPP_BOSH_URL_BASE={{XMPP_BOSH_URL_BASE}}
      # - XMPP_DOMAIN={{XMPP_DOMAIN}}
      # - XMPP_GUEST_DOMAIN={{XMPP_GUEST_DOMAIN}}
      # - XMPP_MUC_DOMAIN={{XMPP_MUC_DOMAIN}}
      # - XMPP_RECORDER_DOMAIN={{XMPP_RECORDER_DOMAIN}}
      # - ENABLE_XMPP_WEBSOCKET={{ENABLE_XMPP_WEBSOCKET}}
      #Aqui é a fronteira 
      - ENABLE_LETSENCRYPT={{ENABLE_LETSENCRYPT}}
      - ENABLE_HTTP_REDIRECT={{ENABLE_HTTP_REDIRECT}}
      - ENABLE_HSTS={{ENABLE_HSTS}}
      - ENABLE_XMPP_WEBSOCKET={{ENABLE_XMPP_WEBSOCKET}}
      - DISABLE_HTTPS={{DISABLE_HTTPS}}
      - LETSENCRYPT_DOMAIN={{LETSENCRYPT_DOMAIN}}
      - LETSENCRYPT_EMAIL={{LETSENCRYPT_EMAIL}}
      - LETSENCRYPT_USE_STAGING={{LETSENCRYPT_USE_STAGING}}
      - PUBLIC_URL={{PUBLIC_URL}}
      - TZ={{TZ}}
      - AMPLITUDE_ID={{AMPLITUDE_ID}}
      - ANALYTICS_SCRIPT_URLS={{ANALYTICS_SCRIPT_URLS}}
      - ANALYTICS_WHITELISTED_EVENTS={{ANALYTICS_WHITELISTED_EVENTS}}
      - BRIDGE_CHANNEL={{BRIDGE_CHANNEL}}
      - CALLSTATS_CUSTOM_SCRIPT_URL={{CALLSTATS_CUSTOM_SCRIPT_URL}}
      - CALLSTATS_ID={{CALLSTATS_ID}}
      - CALLSTATS_SECRET={{CALLSTATS_SECRET}}
      - CHROME_EXTENSION_BANNER_JSON={{CHROME_EXTENSION_BANNER_JSON}}
      - CONFCODE_URL={{CONFCODE_URL}}
      - CONFIG_EXTERNAL_CONNECT={{CONFIG_EXTERNAL_CONNECT}}
      - DEPLOYMENTINFO_ENVIRONMENT={{DEPLOYMENTINFO_ENVIRONMENT}}
      - DEPLOYMENTINFO_ENVIRONMENT_TYPE={{DEPLOYMENTINFO_ENVIRONMENT_TYPE}}
      - DEPLOYMENTINFO_USERREGION={{DEPLOYMENTINFO_USERREGION}}
      - DIALIN_NUMBERS_URL={{DIALIN_NUMBERS_URL}}
      - DIALOUT_AUTH_URL={{DIALOUT_AUTH_URL}}
      - DIALOUT_CODES_URL={{DIALOUT_CODES_URL}}
      - DROPBOX_APPKEY={{DROPBOX_APPKEY}}
      - DROPBOX_REDIRECT_URI={{DROPBOX_REDIRECT_URI}}
      - DYNAMIC_BRANDING_URL={{DYNAMIC_BRANDING_URL}}
      - ENABLE_AUDIO_PROCESSING={{ENABLE_AUDIO_PROCESSING}}
      - ENABLE_AUTH={{ENABLE_AUTH}}
      - ENABLE_CALENDAR={{ENABLE_CALENDAR}}
      - ENABLE_FILE_RECORDING_SERVICE={{ENABLE_FILE_RECORDING_SERVICE}}
      - ENABLE_FILE_RECORDING_SERVICE_SHARING={{ENABLE_FILE_RECORDING_SERVICE_SHARING}}
      - ENABLE_GUESTS={{ENABLE_GUESTS}}
      - ENABLE_IPV6={{ENABLE_IPV6}}
      - ENABLE_LIPSYNC={{ENABLE_LIPSYNC}}
      - ENABLE_NO_AUDIO_DETECTION={{ENABLE_NO_AUDIO_DETECTION}}
      - ENABLE_P2P={{ENABLE_P2P}}
      - ENABLE_PREJOIN_PAGE={{ENABLE_PREJOIN_PAGE}}
      - ENABLE_WELCOME_PAGE={{ENABLE_WELCOME_PAGE}}
      - ENABLE_CLOSE_PAGE={{ENABLE_CLOSE_PAGE}}
      - ENABLE_RECORDING={{ENABLE_RECORDING}}
      - ENABLE_REMB={{ENABLE_REMB}}
      - ENABLE_REQUIRE_DISPLAY_NAME={{ENABLE_REQUIRE_DISPLAY_NAME}}
      - ENABLE_SIMULCAST={{ENABLE_SIMULCAST}}
      - ENABLE_STATS_ID={{ENABLE_STATS_ID}}
      - ENABLE_STEREO={{ENABLE_STEREO}}
      - ENABLE_SUBDOMAINS={{ENABLE_SUBDOMAINS}}
      - ENABLE_TALK_WHILE_MUTED={{ENABLE_TALK_WHILE_MUTED}}
      - ENABLE_TCC={{ENABLE_TCC}}
      - ENABLE_TRANSCRIPTIONS={{ENABLE_TRANSCRIPTIONS}}
      - ETHERPAD_PUBLIC_URL={{ETHERPAD_PUBLIC_URL}}
      - ETHERPAD_URL_BASE={{ETHERPAD_URL_BASE}}
      - GOOGLE_ANALYTICS_ID={{GOOGLE_ANALYTICS_ID}}
      - GOOGLE_API_APP_CLIENT_ID={{GOOGLE_API_APP_CLIENT_ID}}
      - INVITE_SERVICE_URL={{INVITE_SERVICE_URL}}
      - JICOFO_AUTH_USER={{JICOFO_AUTH_USER}}
      - MATOMO_ENDPOINT={{MATOMO_ENDPOINT}}
      - MATOMO_SITE_ID={{MATOMO_SITE_ID}}
      - MICROSOFT_API_APP_CLIENT_ID={{MICROSOFT_API_APP_CLIENT_ID}}
      - NGINX_RESOLVER={{NGINX_RESOLVER}}
      - NGINX_WORKER_PROCESSES={{NGINX_WORKER_PROCESSES}}
      - NGINX_WORKER_CONNECTIONS={{NGINX_WORKER_CONNECTIONS}}
      - PEOPLE_SEARCH_URL={{PEOPLE_SEARCH_URL}}
      - RESOLUTION={{RESOLUTION}}
      - RESOLUTION_MIN={{RESOLUTION_MIN}}
      - RESOLUTION_WIDTH={{RESOLUTION_WIDTH}}
      - RESOLUTION_WIDTH_MIN={{RESOLUTION_WIDTH_MIN}}
      - START_AUDIO_ONLY={{START_AUDIO_ONLY}}
      - START_AUDIO_MUTED={{START_AUDIO_MUTED}}
      - DISABLE_AUDIO_LEVELS={{DISABLE_AUDIO_LEVELS}}
      - ENABLE_NOISY_MIC_DETECTION={{ENABLE_NOISY_MIC_DETECTION}}
      - START_BITRATE={{START_BITRATE}}
      - DESKTOP_SHARING_FRAMERATE_MIN={{DESKTOP_SHARING_FRAMERATE_MIN}}
      - DESKTOP_SHARING_FRAMERATE_MAX={{DESKTOP_SHARING_FRAMERATE_MAX}}
      - START_VIDEO_MUTED={{START_VIDEO_MUTED}}
      - TESTING_CAP_SCREENSHARE_BITRATE={{TESTING_CAP_SCREENSHARE_BITRATE}}
      - TESTING_OCTO_PROBABILITY={{TESTING_OCTO_PROBABILITY}}
      - XMPP_AUTH_DOMAIN={{XMPP_AUTH_DOMAIN}}
      - XMPP_BOSH_URL_BASE={{XMPP_BOSH_URL_BASE}}
      - XMPP_DOMAIN={{XMPP_DOMAIN}}
      - XMPP_GUEST_DOMAIN={{XMPP_GUEST_DOMAIN}}
      - XMPP_MUC_DOMAIN={{XMPP_MUC_DOMAIN}}
      - XMPP_RECORDER_DOMAIN={{XMPP_RECORDER_DOMAIN}}
      - TOKEN_AUTH_URL={{TOKEN_AUTH_URL}}
    networks:
      meet.jitsi:
        aliases:
          - {{XMPP_DOMAIN}}

    # XMPP server
  prosody:
    image: {{IMAGEM_NOME_PROSODY}}:{{ IMAGEM_TAG }}
    restart: {{RESTART_POLICY}}
    container_name: {{ CONTAINER_NOME_PROSODY }}
    ports:
      - '5222:5222'
      - '5347:5347'
      - '5280:5280'
    volumes:
      - {{ INSTALACAO_PASTA_PROSODY }}/config:/config:Z
      - {{ INSTALACAO_PASTA_PROSODY }}/prosody-plugins-custom:/prosody-plugins-custom:Z
    environment:
      # - AUTH_TYPE={{AUTH_TYPE}}
      # - ENABLE_AUTH={{ENABLE_AUTH}}
      # - ENABLE_GUESTS={{ENABLE_GUESTS}}
      # - ENABLE_LOBBY={{ENABLE_LOBBY}}
      # - GLOBAL_MODULES={{GLOBAL_MODULES}}
      # - GLOBAL_CONFIG={{GLOBAL_CONFIG}}
      # - LDAP_URL={{LDAP_URL}}
      # - "LDAP_BASE={{LDAP_BASE}}"
      # - "LDAP_BINDDN={{LDAP_BINDDN}}"
      # - LDAP_BINDPW={{LDAP_BINDPW}}
      # - "LDAP_FILTER={{LDAP_FILTER}}"
      # - LDAP_AUTH_METHOD={{LDAP_AUTH_METHOD}}
      # - LDAP_VERSION={{LDAP_VERSION}}
      # - LDAP_USE_TLS={{LDAP_USE_TLS}}
      # - LDAP_TLS_CIPHERS={{LDAP_TLS_CIPHERS}}
      # - LDAP_TLS_CHECK_PEER={{LDAP_TLS_CHECK_PEER}}
      # - LDAP_TLS_CACERT_FILE={{LDAP_TLS_CACERT_FILE}}
      # - LDAP_TLS_CACERT_DIR={{LDAP_TLS_CACERT_DIR}}
      # - LDAP_START_TLS={{LDAP_START_TLS}}
      # - XMPP_DOMAIN={{XMPP_DOMAIN}}
      # - XMPP_AUTH_DOMAIN={{XMPP_AUTH_DOMAIN}}
      # - XMPP_GUEST_DOMAIN={{XMPP_GUEST_DOMAIN}}
      # - XMPP_MUC_DOMAIN={{XMPP_MUC_DOMAIN}}
      # - XMPP_INTERNAL_MUC_DOMAIN={{XMPP_INTERNAL_MUC_DOMAIN}}
      # - XMPP_MODULES={{XMPP_MODULES}}
      # - XMPP_MUC_MODULES={{XMPP_MUC_MODULES}}
      # - XMPP_INTERNAL_MUC_MODULES={{XMPP_INTERNAL_MUC_MODULES}}
      # - XMPP_RECORDER_DOMAIN={{XMPP_RECORDER_DOMAIN}}
      # - JICOFO_COMPONENT_SECRET={{JICOFO_COMPONENT_SECRET}}
      # - JICOFO_AUTH_USER={{JICOFO_AUTH_USER}}
      # - JICOFO_AUTH_PASSWORD={{JICOFO_AUTH_PASSWORD}}
      # - JVB_AUTH_USER={{JVB_AUTH_USER}}
      # - JVB_AUTH_PASSWORD={{JVB_AUTH_PASSWORD}}
      # - JIGASI_XMPP_USER={{JIGASI_XMPP_USER}}
      # - JIGASI_XMPP_PASSWORD={{JIGASI_XMPP_PASSWORD}}
      # - JIBRI_XMPP_USER={{JIBRI_XMPP_USER}}
      # - JIBRI_XMPP_PASSWORD={{JIBRI_XMPP_PASSWORD}}
      # - JIBRI_RECORDER_USER={{JIBRI_RECORDER_USER}}
      # - JIBRI_RECORDER_PASSWORD={{JIBRI_RECORDER_PASSWORD}}
      # - JWT_APP_ID={{JWT_APP_ID}}
      # - JWT_APP_SECRET={{JWT_APP_SECRET}}
      # - JWT_ACCEPTED_ISSUERS={{JWT_ACCEPTED_ISSUERS}}
      # - JWT_ACCEPTED_AUDIENCES={{JWT_ACCEPTED_AUDIENCES}}
      # - JWT_ASAP_KEYSERVER={{JWT_ASAP_KEYSERVER}}
      # - JWT_ALLOW_EMPTY={{JWT_ALLOW_EMPTY}}
      # - JWT_AUTH_TYPE={{JWT_AUTH_TYPE}}
      # - JWT_TOKEN_AUTH_MODULE={{JWT_TOKEN_AUTH_MODULE}}
      # - LOG_LEVEL={{LOG_LEVEL}}
      # - TZ={{TZ}}
      # - XMPP_CROSS_DOMAIN={{XMPP_CROSS_DOMAIN}}
      # - ENABLE_XMPP_WEBSOCKET={{ENABLE_XMPP_WEBSOCKET}}
      ##Aqui é uma fronteira
      - AUTH_TYPE={{AUTH_TYPE}}
      - ENABLE_AUTH={{ENABLE_AUTH}}
      - ENABLE_GUESTS={{ENABLE_GUESTS}}
      - ENABLE_LOBBY={{ENABLE_LOBBY}}
      - ENABLE_XMPP_WEBSOCKET={{ENABLE_XMPP_WEBSOCKET}}
      - GLOBAL_MODULES={{GLOBAL_MODULES}}
      - GLOBAL_CONFIG={{GLOBAL_CONFIG}}
      - LDAP_URL={{LDAP_URL}}
      - LDAP_BASE={{LDAP_BASE}}
      - LDAP_BINDDN={{LDAP_BINDDN}}
      - LDAP_BINDPW={{LDAP_BINDPW}}
      - LDAP_FILTER={{LDAP_FILTER}}
      - LDAP_AUTH_METHOD={{LDAP_AUTH_METHOD}}
      - LDAP_VERSION={{LDAP_VERSION}}
      - LDAP_USE_TLS={{LDAP_USE_TLS}}
      - LDAP_TLS_CIPHERS={{LDAP_TLS_CIPHERS}}
      - LDAP_TLS_CHECK_PEER={{LDAP_TLS_CHECK_PEER}}
      - LDAP_TLS_CACERT_FILE={{LDAP_TLS_CACERT_FILE}}
      - LDAP_TLS_CACERT_DIR={{LDAP_TLS_CACERT_DIR}}
      - LDAP_START_TLS={{LDAP_START_TLS}}
      - XMPP_DOMAIN={{XMPP_DOMAIN}}
      - XMPP_AUTH_DOMAIN={{XMPP_AUTH_DOMAIN}}
      - XMPP_GUEST_DOMAIN={{XMPP_GUEST_DOMAIN}}
      - XMPP_MUC_DOMAIN={{XMPP_MUC_DOMAIN}}
      - XMPP_INTERNAL_MUC_DOMAIN={{XMPP_INTERNAL_MUC_DOMAIN}}
      - XMPP_MODULES={{XMPP_MODULES}}
      - XMPP_MUC_MODULES={{XMPP_MUC_MODULES}}
      - XMPP_INTERNAL_MUC_MODULES={{XMPP_INTERNAL_MUC_MODULES}}
      - XMPP_RECORDER_DOMAIN={{XMPP_RECORDER_DOMAIN}}
      - XMPP_CROSS_DOMAIN={{XMPP_CROSS_DOMAIN}}
      - JICOFO_COMPONENT_SECRET={{JICOFO_COMPONENT_SECRET}}
      - JICOFO_AUTH_USER={{JICOFO_AUTH_USER}}
      - JICOFO_AUTH_PASSWORD={{JICOFO_AUTH_PASSWORD}}
      - JVB_AUTH_USER={{JVB_AUTH_USER}}
      - JVB_AUTH_PASSWORD={{JVB_AUTH_PASSWORD}}
      - JIGASI_XMPP_USER={{JIGASI_XMPP_USER}}
      - JIGASI_XMPP_PASSWORD={{JIGASI_XMPP_PASSWORD}}
      - JIBRI_XMPP_USER={{JIBRI_XMPP_USER}}
      - JIBRI_XMPP_PASSWORD={{JIBRI_XMPP_PASSWORD}}
      - JIBRI_RECORDER_USER={{JIBRI_RECORDER_USER}}
      - JIBRI_RECORDER_PASSWORD={{JIBRI_RECORDER_PASSWORD}}
      - JWT_APP_ID={{JWT_APP_ID}}
      - JWT_APP_SECRET={{JWT_APP_SECRET}}
      - JWT_ACCEPTED_ISSUERS={{JWT_ACCEPTED_ISSUERS}}
      - JWT_ACCEPTED_AUDIENCES={{JWT_ACCEPTED_AUDIENCES}}
      - JWT_ASAP_KEYSERVER={{JWT_ASAP_KEYSERVER}}
      - JWT_ALLOW_EMPTY={{JWT_ALLOW_EMPTY}}
      - JWT_AUTH_TYPE={{JWT_AUTH_TYPE}}
      - JWT_TOKEN_AUTH_MODULE={{JWT_TOKEN_AUTH_MODULE}}
      - LOG_LEVEL={{LOG_LEVEL}}
      - PUBLIC_URL={{PUBLIC_URL}}
      - TZ={{TZ}}
    networks:
      meet.jitsi:
        aliases:
          - {{XMPP_SERVER}}

  # Focus component
  jicofo:
    image: {{IMAGEM_NOME_JICOFO}}:{{ IMAGEM_TAG }}
    restart: {{RESTART_POLICY}}
    container_name: {{ CONTAINER_NOME_JICOFO }}
    volumes:
      - {{ INSTALACAO_PASTA_JICOFO }}:/config:Z
    environment:
      - AUTH_TYPE={{AUTH_TYPE}}
      - BRIDGE_AVG_PARTICIPANT_STRESS={{BRIDGE_AVG_PARTICIPANT_STRESS}}
      - BRIDGE_STRESS_THRESHOLD={{BRIDGE_STRESS_THRESHOLD}}
      - ENABLE_AUTH={{ENABLE_AUTH}}
      - ENABLE_AUTO_OWNER={{ENABLE_AUTO_OWNER}}
      - ENABLE_CODEC_VP8={{ENABLE_CODEC_VP8}}
      - ENABLE_CODEC_VP9={{ENABLE_CODEC_VP9}}
      - ENABLE_CODEC_H264={{ENABLE_CODEC_H264}}
      - ENABLE_RECORDING={{ENABLE_RECORDING}}
      - ENABLE_SCTP={{ENABLE_SCTP}}
      - JICOFO_COMPONENT_SECRET={{JICOFO_COMPONENT_SECRET}}
      - JICOFO_AUTH_USER={{JICOFO_AUTH_USER}}
      - JICOFO_AUTH_PASSWORD={{JICOFO_AUTH_PASSWORD}}
      - JICOFO_ENABLE_BRIDGE_HEALTH_CHECKS={{JICOFO_ENABLE_BRIDGE_HEALTH_CHECKS}}
      - JICOFO_CONF_INITIAL_PARTICIPANT_WAIT_TIMEOUT={{JICOFO_CONF_INITIAL_PARTICIPANT_WAIT_TIMEOUT}}
      - JICOFO_CONF_SINGLE_PARTICIPANT_TIMEOUT={{JICOFO_CONF_SINGLE_PARTICIPANT_TIMEOUT}}
      - JICOFO_ENABLE_HEALTH_CHECKS={{JICOFO_ENABLE_HEALTH_CHECKS}}
      - JICOFO_SHORT_ID={{JICOFO_SHORT_ID}}
      - JICOFO_RESERVATION_ENABLED={{JICOFO_RESERVATION_ENABLED}}
      - JICOFO_RESERVATION_REST_BASE_URL={{JICOFO_RESERVATION_REST_BASE_URL}}     
      - JIBRI_BREWERY_MUC={{JIBRI_BREWERY_MUC}}   
      - JIBRI_REQUEST_RETRIES={{JIBRI_REQUEST_RETRIES}}
      - JIBRI_PENDING_TIMEOUT={{JIBRI_PENDING_TIMEOUT}}
      - JIGASI_BREWERY_MUC={{JIGASI_BREWERY_MUC}}}
      - JIGASI_SIP_URI={{JIGASI_SIP_URI}}
      - JVB_BREWERY_MUC={{JVB_BREWERY_MUC}}
      - MAX_BRIDGE_PARTICIPANTS={{MAX_BRIDGE_PARTICIPANTS}}
      - OCTO_BRIDGE_SELECTION_STRATEGY={{OCTO_BRIDGE_SELECTION_STRATEGY}}
      - TZ={{TZ}}   
      - XMPP_DOMAIN={{XMPP_DOMAIN}}
      - XMPP_AUTH_DOMAIN={{XMPP_AUTH_DOMAIN}}
      - XMPP_INTERNAL_MUC_DOMAIN={{XMPP_INTERNAL_MUC_DOMAIN}}
      - XMPP_MUC_DOMAIN={{XMPP_MUC_DOMAIN}}
      - XMPP_SERVER={{XMPP_SERVER}}
      ##Aqui é uma fronteira
      - AUTH_TYPE={{AUTH_TYPE}}
      - BRIDGE_AVG_PARTICIPANT_STRESS={{BRIDGE_AVG_PARTICIPANT_STRESS}}
      - BRIDGE_STRESS_THRESHOLD={{BRIDGE_STRESS_THRESHOLD}}
      - ENABLE_AUTH={{ENABLE_AUTH}}
      - ENABLE_AUTO_OWNER={{ENABLE_AUTO_OWNER}}
      - ENABLE_CODEC_VP8={{ENABLE_CODEC_VP8}}
      - ENABLE_CODEC_VP9={{ENABLE_CODEC_VP9}}
      - ENABLE_CODEC_H264={{ENABLE_CODEC_H264}}
      - ENABLE_RECORDING={{ENABLE_RECORDING}}
      - ENABLE_SCTP={{ENABLE_SCTP}}
      - JICOFO_COMPONENT_SECRET={{JICOFO_COMPONENT_SECRET}}
      - JICOFO_AUTH_USER={{JICOFO_AUTH_USER}}
      - JICOFO_AUTH_PASSWORD={{JICOFO_AUTH_PASSWORD}}
      - JICOFO_ENABLE_BRIDGE_HEALTH_CHECKS={{JICOFO_ENABLE_BRIDGE_HEALTH_CHECKS}}
      - JICOFO_CONF_INITIAL_PARTICIPANT_WAIT_TIMEOUT={{JICOFO_CONF_INITIAL_PARTICIPANT_WAIT_TIMEOUT}}
      - JICOFO_CONF_SINGLE_PARTICIPANT_TIMEOUT={{JICOFO_CONF_SINGLE_PARTICIPANT_TIMEOUT}}
      - JICOFO_ENABLE_HEALTH_CHECKS={{JICOFO_ENABLE_HEALTH_CHECKS}}
      - JICOFO_SHORT_ID={{JICOFO_SHORT_ID}}
      - JICOFO_RESERVATION_ENABLED={{JICOFO_RESERVATION_ENABLED}}
      - JICOFO_RESERVATION_REST_BASE_URL={{JICOFO_RESERVATION_REST_BASE_URL}}
      - JIBRI_BREWERY_MUC={{JIBRI_BREWERY_MUC}}
      - JIBRI_REQUEST_RETRIES={{JIBRI_REQUEST_RETRIES}}
      - JIBRI_PENDING_TIMEOUT={{JIBRI_PENDING_TIMEOUT}}
      - JIGASI_BREWERY_MUC={{JIGASI_BREWERY_MUC}}
      - JIGASI_SIP_URI={{JIGASI_SIP_URI}}
      - JVB_BREWERY_MUC={{JVB_BREWERY_MUC}}
      - MAX_BRIDGE_PARTICIPANTS={{MAX_BRIDGE_PARTICIPANTS}}
      - OCTO_BRIDGE_SELECTION_STRATEGY={{OCTO_BRIDGE_SELECTION_STRATEGY}}
      - TZ={{TZ}}
      - XMPP_DOMAIN={{XMPP_DOMAIN}}
      - XMPP_AUTH_DOMAIN={{XMPP_AUTH_DOMAIN}}
      - XMPP_INTERNAL_MUC_DOMAIN={{XMPP_INTERNAL_MUC_DOMAIN}}
      - XMPP_MUC_DOMAIN={{XMPP_MUC_DOMAIN}}
      - XMPP_SERVER={{XMPP_SERVER}}
    depends_on:
      - prosody
    networks:
      meet.jitsi:

  # Video bridge
  jvb:
    image: {{IMAGEM_NOME_JVB}}:{{ IMAGEM_TAG }}
    restart: {{RESTART_POLICY}}
    container_name: {{ CONTAINER_NOME_JVB }}
    ports:
      - '{{JVB_PORT}}:{{JVB_PORT}}/udp'
      - '{{JVB_TCP_PORT}}:{{JVB_TCP_PORT}}'
      - '{{JVB_COLIBRI_PORT}}:8080'
      - '4096:4096/udp'
      - '9090:9090'
    volumes:
      - {{ INSTALACAO_PASTA_JVB }}:/config:Z
    environment:
      - DOCKER_HOST_ADDRESS={{DOCKER_HOST_ADDRESS}}
      - XMPP_AUTH_DOMAIN={{XMPP_AUTH_DOMAIN}}
      - XMPP_INTERNAL_MUC_DOMAIN={{XMPP_INTERNAL_MUC_DOMAIN}}
      - XMPP_SERVER={{XMPP_SERVER}}
      - JVB_AUTH_USER={{JVB_AUTH_USER}}
      - JVB_AUTH_PASSWORD={{JVB_AUTH_PASSWORD}}
      - JVB_BREWERY_MUC={{JVB_BREWERY_MUC}}
      - JVB_PORT={{JVB_PORT}}
      - JVB_TCP_HARVESTER_DISABLED={{JVB_TCP_HARVESTER_DISABLED}}
      - JVB_TCP_PORT={{JVB_TCP_PORT}}
      - JVB_TCP_MAPPED_PORT={{JVB_TCP_MAPPED_PORT}}
      - JVB_STUN_SERVERS={{JVB_STUN_SERVERS}}
      - JVB_ENABLE_APIS={{JVB_ENABLE_APIS}}
      - JVB_WS_DOMAIN={{JVB_WS_DOMAIN}}
      - JVB_WS_SERVER_ID={{JVB_WS_SERVER_ID}}
      - PUBLIC_URL={{PUBLIC_URL}}
      - TZ={{TZ}}
      - ENABLE_COLIBRI_WEBSOCKET={{ENABLE_COLIBRI_WEBSOCKET}}
    depends_on:
      - prosody
    networks:
      meet.jitsi:
        aliases:
          - jvb.meet.jitsi

# Custom network so all services can communicate using a FQDN
networks:
  meet.jitsi: